import React from "react";
import { IoBagHandleOutline } from "react-icons/io5";
import { IoIosArrowRoundForward } from "react-icons/io";
import { useState } from "react";
import { IoIosArrowRoundDown } from "react-icons/io";

export default function App() {
  const [isOpen, setIsOpen] = useState(false);

  const scrollToSection = (id) => {
    const section = document.getElementById(id);
    if (section) {
      section.scrollIntoView({ behavior: "smooth" });
      setIsOpen(false); // Close the mobile menu after clicking
    }
  };

  const features = [
    {
      title: "One-Click Analysis",
      description:
        "Simply click the extension icon on any job posting page to instantly analyze the description.",
    },
    {
      title: "AI-Powered Questions",
      description:
        "Get technical, behavioral, and role-specific questions generated by our advanced AI model.",
    },
    {
      title: "Answer Guidance",
      description:
        "Receive tips and guidance on how to structure your answers for each question.",
    },
  ];
  const howItWorks = [
    {
      title: "Find a Job",
      description:
        "Browse job listings on your favorite job boards like LinkedIn, Indeed, or company career pages.",
    },
    {
      title: "Click the Extension",
      description:
        "With the job description open, click our extension icon in your browser toolbar.",
    },
    {
      title: "Get Prepared",
      description:
        "Review the generated questions and suggested answers to prepare for your interview.",
    },
  ];

  return (
    <div className="overflow-x-clip">
      <nav className="flex items-center justify-between lg:px-16 py-5 border-b-[1px] border-gray-300 px-5">
        <div className="flex items-center space-x-4">
          <IoBagHandleOutline size={25} color="black" />
          <h1 className="text-xl font-bold">InterviewPrep</h1>
        </div>
        <div className="lg:hidden">
          <button className="text-2xl" onClick={() => setIsOpen(!isOpen)}>
            ☰
          </button>
        </div>
        <ul
          className={`font-semibold flex flex-col lg:flex-row items-center gap-5 lg:gap-8 absolute lg:static top-16 left-0 w-full lg:w-auto bg-white lg:bg-transparent shadow-md lg:shadow-none p-5 lg:p-0 transition-all duration-300 ${
            isOpen ? "flex" : "hidden"
          } lg:flex`}
        >
          <li
            className="cursor-pointer"
            onClick={() => scrollToSection("features")}
          >
            Features
          </li>
          <li
            className="cursor-pointer"
            onClick={() => scrollToSection("how-it-works")}
          >
            How it works
          </li>
          <button className="py-2 text-sm text-white bg-black rounded-lg px-7">
            Install Extension
          </button>
        </ul>
      </nav>

      <div className="bg-[#f9f9fa] w-screen p-10 flex flex-col-reverse lg:flex-row justify-around items-center text-center lg:text-left gap-5">
        <div className="text-center space-y-7">
          <h1 className="text-2xl font-bold md:text-4xl xl:text-6xl">
            Ace Your Job Interviews <br /> with AI-Generated <br /> Questions
          </h1>
          <p className="max-w-xl text-lg font-semibold text-center text-gray-500 lg:mx-auto">
            Our browser extension automatically analyzes job descriptions and
            generates tailored interview questions to help you prepare and land
            your dream job.
          </p>
          <div className="flex flex-col items-center justify-center gap-5 md:flex-row">
            <button className="flex items-center gap-2 py-2 text-sm text-white bg-black rounded-md cursor-pointer px-7">
              <h1>Install Now</h1>
              <IoIosArrowRoundForward size={23} color="white" />
            </button>
            <button className="bg-white border-[1px] border-slate-300 text-black px-7 py-2 rounded-md text-sm cursor-pointer">
              Learn More
            </button>
          </div>
        </div>
      </div>

      <div
        id="features"
        className="flex flex-col items-center justify-center gap-6 my-24"
      >
        <button className="flex items-center gap-2 py-2 text-sm text-white bg-black rounded-md px-7">
          <h1 className="text-sm font-semibold">Features</h1>
        </button>

        <div className="space-y-3">
          <h1 className="text-2xl font-bold text-center">
            Everything You Need to Prepare for Your Interview
          </h1>
          <p className="max-w-sm mx-auto text-lg font-semibold text-center text-gray-500 lg:mx-0 md:max-w-xl">
            Our extension uses advanced AI to analyze job descriptions and
            generate relevant interview questions tailored to the position.
          </p>
        </div>

        <div className="flex flex-col gap-8 justify-evenly md:flex-row">
          {features.map((i, id) => (
            <div
              className="border-[1px] border-gray-300 p-8 max-w-xs space-y-4"
              key={id}
            >
              <h1 className="text-xl font-bold text-center">{i.title}</h1>
              <p className="max-w-xl text-sm font-semibold text-center text-gray-500 lg:mx-0">
                {i.description}
              </p>
            </div>
          ))}
        </div>
      </div>

      <div
        id="how-it-works"
        className="flex items-center justify-center flex-col my-10 p-10 gap-6 bg-[#f9f9fa] w-screen"
      >
        <button className="flex items-center gap-2 py-2 text-sm text-white bg-black rounded-md px-7">
          <h1 className="text-sm font-semibold">How It Works</h1>
        </button>

        <div className="space-y-3">
          <h1 className="text-2xl font-bold text-center">
            Simple Process, Powerful Results
          </h1>
          <p className="max-w-xl text-lg font-semibold text-center text-gray-500 lg:mx-0">
            Our extension seamlessly integrates with your job search process to
            help you prepare for interviews.
          </p>
        </div>

        <div className="flex flex-col items-center gap-8 justify-evenly md:flex-row">
          {howItWorks.map((i, id) => (
            <div
              key={id}
              className="flex flex-col items-center gap-4 md:flex-row"
            >
              <div className="max-w-sm p-8 space-y-4">
                <h1 className="w-8 h-8 py-1 mx-auto text-center text-white bg-black rounded-full">
                  {id + 1}
                </h1>
                <h1 className="text-xl font-bold text-center">{i.title}</h1>
                <p className="max-w-xl text-sm font-semibold text-center text-gray-500">
                  {i.description}
                </p>
              </div>
              {id + 1 !== 3 && (
                <>
                  <IoIosArrowRoundForward
                    size={35}
                    color="black"
                    className="hidden md:block"
                  />
                  <IoIosArrowRoundDown
                    size={35}
                    color="black"
                    className="block md:hidden"
                  />
                </>
              )}
            </div>
          ))}
        </div>
      </div>

      <div
        id="pricing"
        className="flex flex-col items-center justify-center w-screen gap-6 p-10 my-10"
      >
        <div className="space-y-6">
          <h1 className="text-2xl font-bold text-center">
            Ready to Ace Your Next Interview?
          </h1>
          <p className="max-w-xl text-lg font-semibold text-center text-gray-500 lg:mx-0">
            Install our extension today and start preparing for your dream job
            with confidence.
          </p>
          <div className="flex items-center justify-center space-x-5">
            <button className="gap-2 py-2 text-white bg-black rounded-md px-7">
              <h1>Install Now</h1>
            </button>
            <button className="bg-white border-[1px] border-slate-300 text-black px-7 py-2 rounded-md">
              Learn More
            </button>
          </div>
        </div>
      </div>

      <footer className="border-t-[1px] border-gray-300 p-5  px-10 flex-col md:flex-row gap-8 md:gap-0">
        <div className="flex items-center justify-center order-2 space-x-3 md:order-1">
          <IoBagHandleOutline size={25} color="black" />
          <h1 className="text-sm font-semibold text-center">
            © 2025 InterviewPrep. All rights reserved.
          </h1>
        </div>
      </footer>
    </div>
  );
}
